### ISSUE TITLE
[Split] Proposal Travis-Ci configuration

### ISSUE THREAD

**Issue by gianarb** [zendframework/zf2#7401]
Hi! I'm follow the wiki about split flow.

I open this issue to create a discussion about [Travis-Ci](https://travis-ci) configuration..

My starting point is the actual configuration, on it I'm creating this first simple config..
In my opinion is necessary an easy start of point..

```yml
language: php
 
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm
  - hhvm-nightly
 
install:
  - composer selfupdate
  - composer install --no-interaction --prefer-source
 
before_script:
  - php --version
  - cp tests/TestConfiguration.php.travis tests/TestConfiguration.php
 
script:
  - /vendor/bin/phpunit
 
after_script:
  - /vendor/bin/coveralls -v
 
notifications:
  irc: "irc.freenode.org#zftalk.dev"
  email: false
```
[Gist .travis.yml](https://gist.github.com/gianarb/b626247f14ee42e6aaf2)

Another question.. 
We have a IRC bot, can we work with it and disable travis irc notification?
